#!/usr/bin/env node
// Scans rooms/ dirs and regenerates content-index.js for each adventure.
// Run locally after adding new YAML files, or let GitHub Actions do it on push.

const fs   = require('fs');
const path = require('path');

function generateIndex(roomsDir, outFile, sectionOrder) {
  const index = {};
  for (const section of sectionOrder) {
    const dir = path.join(roomsDir, section);
    if (!fs.existsSync(dir)) continue;
    index[`rooms/${section}`] = fs.readdirSync(dir)
      .filter(f => f.endsWith('.yaml'))
      .sort();
  }
  const output = `// Auto-generated by .github/scripts/generate-index.js — do not edit by hand.
// Run: node .github/scripts/generate-index.js
const CONTENT_INDEX = ${JSON.stringify(index, null, 2)};
`;
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, output, 'utf8');
  console.log(`Written: ${outFile}`);
  for (const [key, files] of Object.entries(index)) {
    console.log(`  ${key}: ${files.length} file(s)`);
  }
}

generateIndex(
  path.join(__dirname, '../../Close to God/rooms'),
  path.join(__dirname, '../../Close to God/js/content-index.js'),
  ['central-facility', 'lower-levels', 'side-towers', 'upper-levels', 'hidden', 'deep-levels'],
);

generateIndex(
  path.join(__dirname, '../../the-door/rooms'),
  path.join(__dirname, '../../the-door/js/content-index.js'),
  ['surface', 'facility', 'mines'],
);
