#!/usr/bin/env node
// Scans Close to God/rooms/ and regenerates close-to-god/js/content-index.js.
// Run locally after adding new YAML files, or let GitHub Actions do it on push.

const fs   = require('fs');
const path = require('path');

const ROOMS_DIR = path.join(__dirname, '../../Close to God/rooms');
const OUT_FILE  = path.join(__dirname, '../../close-to-god/js/content-index.js');

const SECTION_ORDER = [
  'central-facility', 'lower-levels', 'side-towers',
  'upper-levels', 'hidden', 'deep-levels',
];

const index = {};
for (const section of SECTION_ORDER) {
  const dir = path.join(ROOMS_DIR, section);
  if (!fs.existsSync(dir)) continue;
  index[`rooms/${section}`] = fs.readdirSync(dir)
    .filter(f => f.endsWith('.yaml'))
    .sort();
}

const output = `// Auto-generated by .github/scripts/generate-index.js — do not edit by hand.
// Run: node .github/scripts/generate-index.js
const CONTENT_INDEX = ${JSON.stringify(index, null, 2)};
`;

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, output, 'utf8');
console.log(`Written: ${OUT_FILE}`);
for (const [key, files] of Object.entries(index)) {
  console.log(`  ${key}: ${files.length} file(s)`);
}
