// Auto-generated by .github/scripts/generate-index.js — do not edit by hand.
// Run: node .github/scripts/generate-index.js
const CONTENT_INDEX = {
  "rooms/central-facility": [
    "billiard-bar.yaml",
    "eating-area.yaml",
    "hangar.yaml",
    "lab.yaml",
    "library.yaml",
    "pool.yaml",
    "sleeping-area.yaml",
    "sport-gym.yaml",
    "winter-garden.yaml"
  ],
  "rooms/lower-levels": [
    "bio-facility.yaml",
    "mechanoid-bay.yaml",
    "outdoors.yaml"
  ],
  "rooms/side-towers": [
    "left-tower.yaml",
    "right-tower.yaml"
  ],
  "rooms/upper-levels": [
    "house-of-god.yaml",
    "lookout-facility.yaml"
  ],
  "rooms/hidden": [
    "ai-core.yaml",
    "airducts.yaml",
    "cloning-facility.yaml",
    "the-burrow.yaml"
  ],
  "rooms/deep-levels": [
    "the-end.yaml",
    "the-jump.yaml",
    "the-shed.yaml",
    "tor-system.yaml"
  ]
};
